import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#0a0c24' },
  container: { flex: 1, paddingHorizontal: 16, backgroundColor: '#0a0c24' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  iconBtn: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.06)' },
  headerTitle: { color: '#fff', fontSize: 22, fontWeight: '800' },
  content: { paddingBottom: 24 },
  sectionTitle: { color: '#fff', marginTop: 12, marginBottom: 8, fontSize: 18, fontWeight: '800' },
  label: { color: '#d8dcf7', marginTop: 8, marginBottom: 6, fontWeight: '600' },
  twoCols: { flexDirection: 'row', gap: 10 },
  col: { flex: 1 },
  input: { borderRadius: 12, borderWidth: 1, borderColor: 'rgba(146,151,214,0.25)', backgroundColor: 'rgba(21,23,58,0.9)', color: '#fff', paddingHorizontal: 12, paddingVertical: 12 },
  textArea: { minHeight: 92, textAlignVertical: 'top' },
  imageRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  imageInput: { flex: 1 },
  imageRemoveBtn: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
  addImageButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#6b5bff', paddingVertical: 12, borderRadius: 12, gap: 8, marginBottom: 8 },
  addImageButtonText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  hint: { color: '#bfc5ed', marginTop: 8, marginBottom: 4, lineHeight: 20 },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2, marginBottom: 2 },
  optionPill: { borderRadius: 999, borderWidth: 1, borderColor: 'rgba(146,151,214,0.3)', paddingHorizontal: 12, paddingVertical: 8 },
  optionPillActive: { backgroundColor: 'rgba(143,125,255,0.22)', borderColor: '#8f7dff' },
  optionText: { color: '#aeb4dc', fontWeight: '500' },
  optionTextActive: { color: '#fff', fontWeight: '700' },
  dateInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(146,151,214,0.25)',
    backgroundColor: 'rgba(21,23,58,0.9)',
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateValue: { color: '#fff' },
  datePlaceholder: { color: '#8389b6' },
  datePickerWrap: {
    marginTop: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(146,151,214,0.35)',
    backgroundColor: '#1b245b',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  legendRow: { flexDirection: 'row', gap: 10, marginBottom: 8, paddingHorizontal: 8 },
  legendItem: {
    flexDirection: 'row', alignItems: 'center', borderRadius: 999, borderWidth: 1,
    borderColor: 'rgba(186,192,241,0.35)', backgroundColor: '#2a3269', paddingHorizontal: 12, paddingVertical: 7,
  },
  legendDot: { width: 10, height: 10, borderRadius: 999, marginRight: 8 },
  legendText: { color: '#e7ebff', fontWeight: '700', fontSize: 12 },
  submitBtn: { marginTop: 16, borderRadius: 12, backgroundColor: '#8f7dff', alignItems: 'center', paddingVertical: 13 },
  submitBtnDisabled: { opacity: 0.5 },
  submitText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  imagesGrid: { flexDirection: 'row', gap: 12, marginTop: 10, marginBottom: 12 },
  imageCard: { width: 100, height: 100, borderRadius: 18, overflow: 'hidden', position: 'relative', borderWidth: 2, borderColor: 'transparent' },
  primaryImageCard: { borderColor: '#8f7dff' },
  previewImage: { width: '100%', height: '100%' },
  addImageCard: { width: 100, height: 100, borderRadius: 18, borderWidth: 2, borderStyle: 'dashed', borderColor: '#8f7dff', justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(143,125,255,0.08)' },
  deleteImageBtn: { position: 'absolute', top: 6, right: 6, backgroundColor: 'rgba(0,0,0,0.6)', width: 28, height: 28, borderRadius: 999, justifyContent: 'center', alignItems: 'center' },
  primaryBadge: { position: 'absolute', bottom: 6, left: 6, backgroundColor: '#8f7dff', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  primaryText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  documentsContainer: { gap: 12, marginTop: 10 },
  documentCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: 'rgba(21,23,58,0.9)', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: 'rgba(146,151,214,0.25)' },
  docTitle: { color: '#fff', fontWeight: '700' },
  docName: { color: '#aeb4dc', marginTop: 4, maxWidth: 160 },
  docStatusBadge: { marginTop: 6, alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  docStatusText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  documentActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  documentActionBtn: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
});

export default styles;
